-- DROP SCHEMA dbo;

CREATE SCHEMA dbo;
-- SOP_DB.dbo.TB_PRD_PLAN_CABLE_SPEC definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_PRD_PLAN_CABLE_SPEC;

CREATE TABLE SOP_DB.dbo.TB_PRD_PLAN_CABLE_SPEC (
	SUL_NO varchar(50) COLLATE Korean_Wansung_CI_AS NOT NULL,
	REV_SEQ varchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL,
	ATWRT01 nvarchar(40) COLLATE Korean_Wansung_CI_AS NULL,
	ATWRT02 nvarchar(40) COLLATE Korean_Wansung_CI_AS NULL,
	ATWRT03 nvarchar(40) COLLATE Korean_Wansung_CI_AS NULL,
	ATWRT04 nvarchar(40) COLLATE Korean_Wansung_CI_AS NULL,
	ATWRT05 nvarchar(40) COLLATE Korean_Wansung_CI_AS NULL,
	REG_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	UPD_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NULL,
	UPD_DATE datetime NULL,
	CONSTRAINT TB_PRD_PLAN_CABLE_SPEC_PK PRIMARY KEY (SUL_NO,REV_SEQ)
);


-- SOP_DB.dbo.TB_PRD_PLAN_LIST definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_PRD_PLAN_LIST;

CREATE TABLE SOP_DB.dbo.TB_PRD_PLAN_LIST (
	SALE_OPP_NO varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	PJT_SHIP int NOT NULL,
	SHIP_SEQ int NOT NULL,
	SHIP_SEQ_LOT int NOT NULL,
	SUL_NO varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	REV_SEQ varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
	PJT_LENGTH numeric(10,2) NULL,
	SHIP_STRT_DATE varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
	SHIP_END_DATE varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
	PRD_STRT_DATE varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
	PRD_END_DATE varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
	PRD_CNFM_STRT_DATE varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
	PRD_CNFM_END_DATE varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
	ITEM_NM nvarchar(300) COLLATE Korean_Wansung_CI_AS NULL,
	NOTE nvarchar(300) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE1 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE2 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	REG_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	UPD_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NULL,
	UPD_DATE datetime NULL,
	CONSTRAINT TB_PRD_PLAN_LIST_PK PRIMARY KEY (SALE_OPP_NO,PJT_SHIP,SHIP_SEQ,SHIP_SEQ_LOT)
);


-- SOP_DB.dbo.TB_PRD_PLAN_MASTER definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_PRD_PLAN_MASTER;

CREATE TABLE SOP_DB.dbo.TB_PRD_PLAN_MASTER (
	QUO_YM varchar(6) COLLATE Korean_Wansung_CI_AS NOT NULL,
	SALE_OPP_NO varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	SALE_OPP_NM nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	PJT_OWNER varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	PJT_STRT_DATE varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
	PJT_EEND_DATE varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
	PJT_REND_DATE varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
	PJT_STATUS varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
	SIMUL_DATA_EXIST_YN varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
	NOTE nvarchar(300) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE1 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE2 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	REG_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	UPD_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NULL,
	UPD_DATE datetime NULL,
	CONSTRAINT TB_PRD_PLAN_MASTER_PK PRIMARY KEY (QUO_YM,SALE_OPP_NO)
);


-- SOP_DB.dbo.TB_SAP_IF_Z_ED_RFC_QPRICE definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_SAP_IF_Z_ED_RFC_QPRICE;

CREATE TABLE SOP_DB.dbo.TB_SAP_IF_Z_ED_RFC_QPRICE (
	SUL_NO nvarchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	SEQ int NOT NULL,
	REV_SEQ nvarchar(5) COLLATE Korean_Wansung_CI_AS NULL,
	MAT_DESC nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	GONG_SEQ int NULL,
	GONG_CD nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	GONG_NM nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	JACK_SEQ int NULL,
	JACK_CD nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	JACK_NM nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	LAYER int NULL,
	SEQNO int NULL,
	MATNR nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	MATNR_NM nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	JAJE_QTY numeric(18,3) NULL,
	JAJE_UNIT nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
	WAERS nvarchar(5) COLLATE Korean_Wansung_CI_AS NULL,
	SPMON numeric(10,3) NULL,
	PRICE numeric(10,3) NULL,
	PRICE_01 numeric(10,3) NULL,
	PRICE_02 numeric(10,3) NULL,
	PRICE_03 numeric(10,3) NULL,
	PRICE_04 numeric(10,3) NULL,
	PRICE_05 numeric(10,3) NULL,
	IN_PRICE numeric(10,3) NULL,
	AMT numeric(18,3) NULL,
	RMK nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	AEDAT datetime NULL,
	AEZET datetime NULL,
	REG_EMP nvarchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NULL,
	CONSTRAINT TB_SAP_IF_Z_ED_RFC_QPRICE_PK PRIMARY KEY (SUL_NO,SEQ)
);


-- SOP_DB.dbo.TB_SAP_WORK_CENTER_MST definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_SAP_WORK_CENTER_MST;

CREATE TABLE SOP_DB.dbo.TB_SAP_WORK_CENTER_MST (
	CATEGORY varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
	PLANT_CD varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
	WORK_CNTR_CD varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	WORK_CNTR_NM nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	NOTE nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	REG_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	UPD_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NULL,
	UPD_DATE datetime NULL,
	CONSTRAINT TB_SAP_WORK_CENTER_MST_PK PRIMARY KEY (CATEGORY,PLANT_CD,WORK_CNTR_CD)
);


-- SOP_DB.dbo.TB_SIMUL_COLOR_MST definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_SIMUL_COLOR_MST;

CREATE TABLE SOP_DB.dbo.TB_SIMUL_COLOR_MST (
	SEQ numeric(38,0) NOT NULL,
	COLOR_CODE varchar(100) COLLATE Korean_Wansung_CI_AS NOT NULL,
	COLOR_NAME nvarchar(100) COLLATE Korean_Wansung_CI_AS NOT NULL,
	CONSTRAINT TB_SIMUL_COLOR_MST_PK PRIMARY KEY (SEQ)
);


-- SOP_DB.dbo.TB_SIMUL_DATA_LOT_MODIFY definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_SIMUL_DATA_LOT_MODIFY;

CREATE TABLE SOP_DB.dbo.TB_SIMUL_DATA_LOT_MODIFY (
	SALE_OPP_NO varchar(50) COLLATE Korean_Wansung_CI_AS NOT NULL,
	PJT_SHIP int NOT NULL,
	SHIP_SEQ int NOT NULL,
	SHIP_SEQ_LOT int NOT NULL,
	SUL_NO varchar(50) COLLATE Korean_Wansung_CI_AS NOT NULL,
	ASSEMBLY int NOT NULL,
	PROCESS_CODE varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	WORK_CNTR_CD varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	WORK_DAYS numeric(2,1) NULL,
	PREPARE_DAYS numeric(2,1) NULL,
	PRD_STRT_DATE varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
	NOTE nvarchar(300) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE1 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE2 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	REG_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	UPD_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NULL,
	UPD_DATE datetime NULL,
	CONSTRAINT TB_SIMUL_DATA_LOT_MODIFY_PK PRIMARY KEY (SALE_OPP_NO,PJT_SHIP,SHIP_SEQ,SHIP_SEQ_LOT,SUL_NO,ASSEMBLY,PROCESS_CODE,WORK_CNTR_CD)
);


-- SOP_DB.dbo.TB_SIMUL_DATA_PJT_MODIFY definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_SIMUL_DATA_PJT_MODIFY;

CREATE TABLE SOP_DB.dbo.TB_SIMUL_DATA_PJT_MODIFY (
	SALE_OPP_NO varchar(50) COLLATE Korean_Wansung_CI_AS NOT NULL,
	PROCESS_CODE varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	WORK_CNTR_CD varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	WORK_DAYS numeric(2,1) NULL,
	PREPARE_DAYS numeric(2,1) NULL,
	PRD_STRT_DATE varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
	NOTE nvarchar(300) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE1 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE2 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	REG_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	UPD_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NULL,
	UPD_DATE datetime NULL,
	CONSTRAINT TB_SIMUL_DATA_PJT_MODIFY_PK PRIMARY KEY (SALE_OPP_NO,PROCESS_CODE,WORK_CNTR_CD)
);


-- SOP_DB.dbo.TB_SIMUL_DEBUG_LOG definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_SIMUL_DEBUG_LOG;

CREATE TABLE SOP_DB.dbo.TB_SIMUL_DEBUG_LOG (
	LOG_ID bigint IDENTITY(1,1) NOT NULL,
	LOG_DTM datetime NULL,
	PROC_NAME sysname COLLATE Korean_Wansung_CI_AS NOT NULL,
	USER_CODE nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	STEP nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	MESSAGE nvarchar(MAX) COLLATE Korean_Wansung_CI_AS NULL,
	KEY1 nvarchar(3000) COLLATE Korean_Wansung_CI_AS NULL,
	KEY2 nvarchar(3000) COLLATE Korean_Wansung_CI_AS NULL,
	KEY3 nvarchar(3000) COLLATE Korean_Wansung_CI_AS NULL,
	CONSTRAINT PK__TB_SIMUL__4364C882A2C90C02 PRIMARY KEY (LOG_ID)
);


-- SOP_DB.dbo.TB_SIMUL_FAC_PC definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_SIMUL_FAC_PC;

CREATE TABLE SOP_DB.dbo.TB_SIMUL_FAC_PC (
	Q_YEAR varchar(4) COLLATE Korean_Wansung_CI_AS NOT NULL,
	PROCESS_CODE varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
	PROCESS_NAME nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	SEQ int NOT NULL,
	PL_CENTER nvarchar(10) COLLATE Korean_Wansung_CI_AS NULL,
	COST_CENTER varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
	COST_CENTER_DESC nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	HUMAN_PRICE numeric(18,4) NULL,
	MACHINE_PRICE numeric(18,4) NULL,
	PROCESS_PRICE numeric(18,4) NULL,
	PROCESS_QTT numeric(10,0) NULL,
	STANDARD_PERSON numeric(10,0) NULL,
	OPER_RATE numeric(10,0) NULL,
	USE_YN varchar(1) COLLATE Korean_Wansung_CI_AS NULL,
	PROCESS_FLAG nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	[CONDITION] nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	PROCESS_DAYS_1 numeric(10,1) NULL,
	PROCESS_DAYS_2 numeric(10,1) NULL,
	WORK_DAYS numeric(2,1) NULL,
	PREPARE_DAYS numeric(2,1) NULL,
	NOTE nvarchar(300) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE1 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE2 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	REG_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	UPD_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NOT NULL,
	UPD_DATE datetime NOT NULL
);


-- SOP_DB.dbo.TB_SIMUL_SUL_ASSY_PROC_LIST definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_SIMUL_SUL_ASSY_PROC_LIST;

CREATE TABLE SOP_DB.dbo.TB_SIMUL_SUL_ASSY_PROC_LIST (
	SUL_NO varchar(50) COLLATE Korean_Wansung_CI_AS NOT NULL,
	ASSEMBLY int NOT NULL,
	PROCESS_CODE varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	CATEGORY varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
	PLANT_CD varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
	WORK_CNTR_CD varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	EQUIP_SPEED float NULL,
	SIMUL_VALUE1 float NULL,
	SIMUL_VALUE2 float NULL,
	SIMUL_VALUE3 float NULL,
	SIMUL_VALUE4 float NULL,
	NOTE nvarchar(300) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE1 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE2 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	REG_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	UPD_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NULL,
	UPD_DATE datetime NULL,
	CONSTRAINT TB_SIMUL_SUL_ASSY_PROC_LIST_PK PRIMARY KEY (SUL_NO,ASSEMBLY,PROCESS_CODE,CATEGORY,PLANT_CD,WORK_CNTR_CD)
);


-- SOP_DB.dbo.TB_SIMUL_VERSION_DATA definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_SIMUL_VERSION_DATA;

CREATE TABLE SOP_DB.dbo.TB_SIMUL_VERSION_DATA (
	SIMUL_VERSION varchar(50) COLLATE Korean_Wansung_CI_AS NOT NULL,
	SEQ int NOT NULL,
	SALE_OPP_NO varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	PJT_SHIP int NULL,
	SHIP_SEQ int NULL,
	SHIP_SEQ_LOT int NULL,
	SUL_NO varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	ASSEMBLY_SEQ int NULL,
	ASSEMBLY int NULL,
	FJ_ASSEMBLY_SEQ int NULL,
	FJ_ASSEMBLY int NULL,
	PROCESS_SEQ int NULL,
	PROCESS_CODE varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	WORK_CNTR_SEQ int NULL,
	WORK_CNTR_CD varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	EQUIP_SPEED float NULL,
	LEAD_TIME float NULL,
	SIMUL_VALUE1 float NULL,
	SIMUL_VALUE2 float NULL,
	SIMUL_VALUE3 float NULL,
	SIMUL_VALUE4 float NULL,
	PRD_CNFM_STRT_DATE date NULL,
	PRD_CNFM_END_DATE date NULL,
	REG_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	UPD_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NULL,
	UPD_DATE datetime NULL,
	CONSTRAINT TB_SIMUL_VERSION_DATA_PK PRIMARY KEY (SIMUL_VERSION,SEQ)
);


-- SOP_DB.dbo.TB_SIMUL_VERSION_MAIN_CONFIG definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_SIMUL_VERSION_MAIN_CONFIG;

CREATE TABLE SOP_DB.dbo.TB_SIMUL_VERSION_MAIN_CONFIG (
	CONFIG_ID int DEFAULT 1 NOT NULL,
	SIMUL_VERSION varchar(50) COLLATE Korean_Wansung_CI_AS NOT NULL,
	REG_USER varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE date NULL,
	CONSTRAINT PK_TB_SIMUL_VERSION_MAIN_CONFIG PRIMARY KEY (CONFIG_ID)
);
ALTER TABLE SOP_DB.dbo.TB_SIMUL_VERSION_MAIN_CONFIG WITH NOCHECK ADD CONSTRAINT CK_TB_SIMUL_VERSION_MAIN_CONFIG_SINGLE_ROW CHECK (([CONFIG_ID]=(1)));


-- SOP_DB.dbo.TB_SIMUL_VERSION_MST definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_SIMUL_VERSION_MST;

CREATE TABLE SOP_DB.dbo.TB_SIMUL_VERSION_MST (
	SIMUL_VERSION varchar(50) COLLATE Korean_Wansung_CI_AS NOT NULL,
	SIMUL_VERSION_DESC nvarchar(100) COLLATE Korean_Wansung_CI_AS NOT NULL,
	USE_YN varchar(1) COLLATE Korean_Wansung_CI_AS NULL,
	NOTE nvarchar(300) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE1 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE2 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	REG_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	UPD_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NULL,
	UPD_DATE datetime NULL,
	CONSTRAINT TB_SIMUL_VERSION_MST_PK PRIMARY KEY (SIMUL_VERSION)
);


-- SOP_DB.dbo.TB_SIMUL_WORK_CENTER_GRP definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_SIMUL_WORK_CENTER_GRP;

CREATE TABLE SOP_DB.dbo.TB_SIMUL_WORK_CENTER_GRP (
	CATEGORY varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
	PLANT_CD varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
	GRP_WORK_CNTR_CD varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	WORK_CNTR_CD varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	SIMUL_PROCESS_CD varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	UPD_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NULL,
	UPD_DATE datetime NULL,
	CONSTRAINT TB_SIMUL_WORK_CENTER_GRP_PK PRIMARY KEY (CATEGORY,PLANT_CD,GRP_WORK_CNTR_CD,WORK_CNTR_CD)
);


-- SOP_DB.dbo.TB_SIMUL_WORK_CENTER_MST definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_SIMUL_WORK_CENTER_MST;

CREATE TABLE SOP_DB.dbo.TB_SIMUL_WORK_CENTER_MST (
	CATEGORY varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
	PLANT_CD varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
	WORK_CNTR_CD varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
	SIMUL_WORK_CNTR_NM nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	SIMUL_SEQ int NULL,
	SIMUL_PROCESS_CD varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	DEFAULT_YN char(1) COLLATE Korean_Wansung_CI_AS NULL,
	SMMP_WORK_CNTR_CD varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	SMMP_WORK_CNTR_NM nvarchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	CABLE_CORE_FLAG varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
	NOTE nvarchar(300) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE1 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	ATTRIBUTE2 nvarchar(100) COLLATE Korean_Wansung_CI_AS NULL,
	REG_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	UPD_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NULL,
	UPD_DATE datetime NULL,
	CONSTRAINT TB_SIMUL_WORK_CENTER_MST_PK PRIMARY KEY (CATEGORY,PLANT_CD,WORK_CNTR_CD)
);


-- SOP_DB.dbo.TB_TEMP_VERSION_DATA definition

-- Drop table

-- DROP TABLE SOP_DB.dbo.TB_TEMP_VERSION_DATA;

CREATE TABLE SOP_DB.dbo.TB_TEMP_VERSION_DATA (
	TEMP_VERSION varchar(50) COLLATE Korean_Wansung_CI_AS NOT NULL,
	SEQ int NOT NULL,
	SALE_OPP_NO varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	PJT_SHIP int NULL,
	SHIP_SEQ int NULL,
	SHIP_SEQ_LOT int NULL,
	SUL_NO varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
	ASSEMBLY_SEQ int NULL,
	ASSEMBLY int NULL,
	FJ_ASSEMBLY_SEQ int NULL,
	FJ_ASSEMBLY int NULL,
	PROCESS_SEQ int NULL,
	PROCESS_CODE varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	WORK_CNTR_SEQ int NULL,
	WORK_CNTR_CD varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	EQUIP_SPEED float NULL,
	LEAD_TIME float NULL,
	SIMUL_VALUE1 float NULL,
	SIMUL_VALUE2 float NULL,
	SIMUL_VALUE3 float NULL,
	SIMUL_VALUE4 float NULL,
	PRD_CNFM_STRT_DATE date NULL,
	PRD_CNFM_END_DATE date NULL,
	REG_EMP varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
	REG_DATE datetime NULL,
	CONSTRAINT TB_TEMP_VERSION_DATA_PK PRIMARY KEY (TEMP_VERSION,SEQ)
);