CREATE PROCEDURE [dbo].[SP_CABLE_PRODUCTION_GET_AUTO_SCHEDULER_SELECT]
(
      @TIMESTAMP_BASE_DATE DATE
    , @P_TEMP_VERSION      VARCHAR(50)
    , @P_USER_CODE         VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
          @P_TEMP_VERSION AS TEMP_VERSION
        , ROW_NUMBER() OVER(
              ORDER BY
                  R.SALE_OPP_NO, R.PJT_SHIP, R.SHIP_SEQ DESC, R.SHIP_SEQ_LOT,
                  R.ASSEMBLY_SEQ, R.FJ_ASSEMBLY_SEQ, R.PROCESS_SEQ, R.INSERT_ORDER
          ) AS SEQ
        , R.SALE_OPP_NO
        , R.PJT_SHIP
        , R.SHIP_SEQ
        , R.SHIP_SEQ_LOT
        , R.SUL_NO
		, R.REV_SEQ
        , R.ASSEMBLY_SEQ
        , R.ASSEMBLY
        , R.FJ_ASSEMBLY_SEQ
        , R.FJ_ASSEMBLY
        , R.PROCESS_SEQ
        , R.PROCESS_CODE
        , ROW_NUMBER() OVER
          (
              PARTITION BY R.SALE_OPP_NO, R.PJT_SHIP, R.SHIP_SEQ, R.SHIP_SEQ_LOT, R.ASSEMBLY, R.FJ_ASSEMBLY_SEQ
              ORDER BY R.PROCESS_SEQ, R.INSERT_ORDER
          ) AS WORK_CNTR_SEQ
        , R.WORK_CNTR_CD
        , R.EQUIP_SPEED
        , R.LEAD_TIME
        , DATEADD(DAY, R.START_TS, @TIMESTAMP_BASE_DATE) AS PRD_CNFM_STRT_DATE
        , DATEADD(DAY, R.END_TS,   @TIMESTAMP_BASE_DATE) AS PRD_CNFM_END_DATE
        , @P_USER_CODE AS REG_EMP
        , GETDATE() AS REG_DATE
    FROM #RESULT_STEP R
    ORDER BY SEQ;
END