CREATE PROCEDURE [dbo].[SP_CABLE_PRODUCTION_GET_SHIPMENT_START_SCHEDULER_INIT]
(
      @TIMESTAMP_BASE_DATE            DATE
    , @TB_PROCESS_WORK_CNTR_TIMESTAMP dbo.UDT_MST_PROCESS_WORK_CNTR_TIMESTAMP READONLY
    , @TB_PRIORITY_PJT_LOT_LEADTIME   dbo.UDT_DATA_CABLE_PJT_LOT_FJ READONLY
    , @TB_FIXED_PJT_LOT_TIMESTAMP     dbo.UDT_DATA_CABLE_PJT_LOT_FJ READONLY
)
AS
BEGIN
    SET NOCOUNT ON;

    -- 1. 전역 타임라인 기초 데이터 로드
    INSERT INTO #WORK_CNTR_TIMESTAMP (PROCESS_CODE, WORK_CNTR_CD, TS_IDX, IS_ASSIGNED)
    SELECT PROCESS_CODE, WORK_CNTR_CD, TIMESTAMP_POINT, 0
    FROM @TB_PROCESS_WORK_CNTR_TIMESTAMP;

    -- 2. 스케줄링 원천 데이터 로드
    INSERT INTO #SRC_FJ (
        SEQ, SALE_OPP_NO, PJT_SHIP, SHIP_SEQ, SHIP_SEQ_LOT, LOT_NO, 
        SUL_NO, REV_SEQ, ASSEMBLY_SEQ, ASSEMBLY, FJ_ASSEMBLY_SEQ, FJ_ASSEMBLY, 
        PROCESS_SEQ, PROCESS_CODE, WORK_CNTR_SEQ, WORK_CNTR_CD, 
        EQUIP_SPEED, LEAD_TIME_DAYS, PREPARE_DAYS, WORK_DAYS, PRD_STRT_DATE
    )
    SELECT 
        PRODUCTION_SEQ, SALE_OPP_NO, PJT_SHIP, SHIP_SEQ, SHIP_SEQ_LOT, LOT_NO, 
        SUL_NO, REV_SEQ, ASSEMBLY_SEQ, ASSEMBLY, FJ_ASSEMBLY_SEQ, FJ_ASSEMBLY, 
        PROCESS_SEQ, PROCESS_CODE, WORK_CNTR_SEQ, WORK_CNTR_CD, 
        EQUIP_SPEED, LEAD_TIME, PREPARE_DAYS, WORK_DAYS, PRD_STRT_DATE
    FROM @TB_PRIORITY_PJT_LOT_LEADTIME;

    -- 3. 프로젝트별-항차별 시작 기준점 계산
    INSERT INTO #SHIP_META (SALE_OPP_NO, PJT_SHIP, SHIP_TS_POINT)
    SELECT SALE_OPP_NO, PJT_SHIP, DATEDIFF(DAY, @TIMESTAMP_BASE_DATE, MIN(PRD_STRT_DATE))
    FROM #SRC_FJ
    GROUP BY SALE_OPP_NO, PJT_SHIP;

    -- 4. 설비 그룹 데이터 로드 (#WC_GRP)
	INSERT INTO #WC_GRP(SIMUL_PROCESS_CD, GRP_WORK_CNTR_CD, WORK_CNTR_CD)
	SELECT SIMUL_PROCESS_CD, GRP_WORK_CNTR_CD, WORK_CNTR_CD
	FROM TB_SIMUL_WORK_CENTER_GRP;
	
	CREATE INDEX IX_WC_GRP_1 ON #WC_GRP(SIMUL_PROCESS_CD, GRP_WORK_CNTR_CD);
	CREATE INDEX IX_WC_GRP_2 ON #WC_GRP(SIMUL_PROCESS_CD, WORK_CNTR_CD);

    -- 5. 기존 우선순위 및 케이블 사양 반영 데이터 구성 (#ASSIGN_BLOCK_DATA)
    INSERT INTO #ASSIGN_BLOCK_DATA (
        ASSIGN_SEQ, SALE_OPP_NO, PJT_SHIP, SHIP_SEQ, SHIP_SEQ_LOT,
        LOT_NO, SUL_NO, REV_SEQ, ATWRT02, ASSEMBLY_SEQ, ASSEMBLY,
        PROCESS_SEQ, PROCESS_CODE
    )
    SELECT
          MIN(P.SEQ) AS ASSIGN_SEQ
        , P.SALE_OPP_NO
        , P.PJT_SHIP
        , P.SHIP_SEQ
        , P.SHIP_SEQ_LOT
        , P.LOT_NO
		, P.SUL_NO
		, PL.REV_SEQ
        , CS.ATWRT02
        , P.ASSEMBLY_SEQ
        , P.ASSEMBLY
        , P.PROCESS_SEQ
        , P.PROCESS_CODE
    FROM @TB_PRIORITY_PJT_LOT_LEADTIME P                         
         INNER JOIN SOP_DB.dbo.TB_PRD_PLAN_LIST PL
                 ON P.SALE_OPP_NO  = PL.SALE_OPP_NO
                AND P.PJT_SHIP     = PL.PJT_SHIP
                AND P.SHIP_SEQ     = PL.SHIP_SEQ
                AND P.SHIP_SEQ_LOT = PL.SHIP_SEQ_LOT
                AND P.SUL_NO       = PL.SUL_NO
         LEFT OUTER JOIN SOP_DB.dbo.TB_PRD_PLAN_CABLE_SPEC CS
                      ON PL.SUL_NO  = CS.SUL_NO
                     AND PL.REV_SEQ = CS.REV_SEQ
    GROUP BY
          P.SALE_OPP_NO, P.PJT_SHIP, P.SHIP_SEQ, P.SHIP_SEQ_LOT,
          P.LOT_NO, P.SUL_NO, PL.REV_SEQ, CS.ATWRT02,
		  P.ASSEMBLY_SEQ, P.ASSEMBLY,
          P.PROCESS_SEQ, P.PROCESS_CODE;

    -- 6. 최종 LOT 배정 순서 구성 (#LOT_ORDER)
    INSERT INTO #LOT_ORDER (
        ASSIGN_SEQ, SALE_OPP_NO, PJT_SHIP, SHIP_SEQ, SHIP_SEQ_LOT,
        LOT_NO, SUL_NO, REV_SEQ, ATWRT02, ASSEMBLY_SEQ, ASSEMBLY,
        PROCESS_SEQ, PROCESS_CODE
    )
    SELECT
        A.ASSIGN_SEQ, A.SALE_OPP_NO, A.PJT_SHIP, A.SHIP_SEQ, A.SHIP_SEQ_LOT,
        A.LOT_NO, A.SUL_NO, A.REV_SEQ, A.ATWRT02, A.ASSEMBLY_SEQ, A.ASSEMBLY,
        A.PROCESS_SEQ, A.PROCESS_CODE
    FROM #ASSIGN_BLOCK_DATA A
    ORDER BY A.ASSIGN_SEQ;

    CREATE UNIQUE CLUSTERED INDEX CX_LOT_ORDER ON #LOT_ORDER(LOT_ORDER_ID);

    -- 7. 수동 데이터 타임라인 선점 및 결과 선입력
    UPDATE T
    SET T.IS_ASSIGNED = 1, T.SALE_OPP_NO = F.SALE_OPP_NO, T.LOT_NO = F.LOT_NO
    FROM #WORK_CNTR_TIMESTAMP T
    JOIN @TB_FIXED_PJT_LOT_TIMESTAMP F ON T.PROCESS_CODE = F.PROCESS_CODE 
                                       AND T.WORK_CNTR_CD = F.WORK_CNTR_CD 
                                       AND T.TS_IDX BETWEEN F.FIXED_TIMESTAMP_POINT 
                                                       AND (F.FIXED_TIMESTAMP_POINT + F.LEAD_TIME - 1);

    INSERT INTO #FINAL_ASSIGN_DATA (SALE_OPP_NO, PJT_SHIP, LOT_NO, PROCESS_CODE, WORK_CNTR_CD, STRT_TS, END_TS, IS_MANUAL, RESULT_STEP)
    SELECT SALE_OPP_NO, PJT_SHIP, LOT_NO, PROCESS_CODE, WORK_CNTR_CD, FIXED_TIMESTAMP_POINT, FIXED_TIMESTAMP_POINT + LEAD_TIME - 1, 1, -1
    FROM @TB_FIXED_PJT_LOT_TIMESTAMP;

END