CREATE PROCEDURE [dbo].[SP_CABLE_PRODUCTION_GET_SHIPMENT_START_SCHEDULER_INIT]
(
      @TIMESTAMP_BASE_DATE            DATE
    , @TB_PROCESS_WORK_CNTR_TIMESTAMP dbo.UDT_MST_PROCESS_WORK_CNTR_TIMESTAMP READONLY
    , @TB_PRIORITY_PJT_LOT_LEADTIME   dbo.UDT_DATA_CABLE_PJT_LOT_FJ READONLY
    , @TB_FIXED_PJT_LOT_TIMESTAMP     dbo.UDT_DATA_CABLE_PJT_LOT_FJ READONLY
)
AS
BEGIN
    -- 설비별 가용 타임라인 초기화
    SELECT * INTO #WORK_CNTR_TIMESTAMP FROM @TB_PROCESS_WORK_CNTR_TIMESTAMP;

    -- 고정(수동 조정) 데이터 초기화
    SELECT * INTO #FIXED_PJT_LOT_DATA FROM @TB_FIXED_PJT_LOT_TIMESTAMP;

    -- 고정된 데이터를 최종 결과에 먼저 삽입 (선점 효과)
    INSERT INTO #FINAL_ASSIGN_DATA (SALE_OPP_NO, PJT_SHIP, LOT_NO, PROCESS_CODE, WORK_CNTR_CODE, STRT_TS, END_TS, IS_MANUAL)
    SELECT SALE_OPP_NO, PJT_SHIP, LOT_NO, PROCESS_CODE, WORK_CNTR_CODE, STRT_TS, END_TS, 1
    FROM #FIXED_PJT_LOT_DATA;

    -- 고정된 시간만큼 설비 가용성 차감 (Update Work Center Timestamp)
    UPDATE T
    SET T.IS_ASSIGNED = 1
    FROM #WORK_CNTR_TIMESTAMP T
    JOIN #FIXED_PJT_LOT_DATA F ON T.WORK_CNTR_CODE = F.WORK_CNTR_CODE 
                               AND T.TS_IDX BETWEEN F.STRT_TS AND F.END_TS;
END