CREATE PROCEDURE [dbo].[SP_CABLE_PRODUCTION_GET_PROCESS_WORK_CNTR_TIMESTAMP]
AS 
BEGIN
    SET NOCOUNT ON; -- 불필요한 행 수 메시지 출력 방지
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    BEGIN TRY
		SELECT A.SIMUL_SEQ
		     , A.SIMUL_PROCESS_CD
		     , A.WORK_CNTR_CD
		     , 0 AS TIMESTAMP_POINT
		  FROM SOP_DB.dbo.TB_SIMUL_WORK_CENTER_MST A
		       INNER JOIN SOP_DB.dbo.TB_SIMUL_FAC_PC B
		               ON A.SIMUL_PROCESS_CD = B.PROCESS_CODE
		              AND B.Q_YEAR = YEAR(GETDATE())
		 ORDER BY A.SIMUL_SEQ
        
    END TRY
    BEGIN CATCH
        -- 에러 처리
        THROW 52001, 'SP_CABLE_PRODUCTION_PROCESS_WORK_CNTR_TIMESTAMP Query error', 1;
    END CATCH
END;