CREATE PROCEDURE [dbo].[SP_CABLE_PRODUCTION_GET_SHIPMENT_START_SCHEDULER_VIRTUAL_RUN]
(
      @P_PREP_PROC_DAYS INT = 1
    , @P_PREP_FJ_DAYS   INT = 1
)
AS
BEGIN
    SET NOCOUNT ON;

    /* =====================================================================================
       1. 가상 환경용 임시 테이블 정의 (기존 로직의 변수/구조 계승)
    ===================================================================================== */
    -- 항차별 독립 설비 타임라인 (각 항차는 서로의 설비 점유를 모름)
    IF OBJECT_ID('tempdb..#V_WORK_CNTR_TIMESTAMP') IS NOT NULL DROP TABLE #V_WORK_CNTR_TIMESTAMP;
    CREATE TABLE #V_WORK_CNTR_TIMESTAMP (
        SALE_OPP_NO     VARCHAR(20),
        PJT_SHIP        INT,
        PROCESS_CODE    VARCHAR(20),
        WORK_CNTR_CD    VARCHAR(20),
        TIMESTAMP_POINT INT,
        PRIMARY KEY (SALE_OPP_NO, PJT_SHIP, PROCESS_CODE, WORK_CNTR_CD)
    );

    -- 항차별 독립 FJ Ready 타임라인
    IF OBJECT_ID('tempdb..#V_FJ_READY_TS') IS NOT NULL DROP TABLE #V_FJ_READY_TS;
    CREATE TABLE #V_FJ_READY_TS (
        SALE_OPP_NO     VARCHAR(20),
        PJT_SHIP        INT,
        LOT_NO          VARCHAR(50),
        ASSEMBLY_SEQ    INT,
        FJ_ASSEMBLY_SEQ INT,
        READY_TS        INT,
        PRIMARY KEY (SALE_OPP_NO, PJT_SHIP, LOT_NO, ASSEMBLY_SEQ, FJ_ASSEMBLY_SEQ)
    );

    -- 기존 로직 내부 루프용 임시 테이블 (Wrapper에서 생성했으면 생략 가능하나 안전을 위해 선언)
    IF OBJECT_ID('tempdb..#PROC_LIST') IS NOT NULL DROP TABLE #PROC_LIST;
    CREATE TABLE #PROC_LIST (RN INT IDENTITY(1,1), PROCESS_SEQ INT, PROCESS_CODE VARCHAR(20));

    IF OBJECT_ID('tempdb..#FJ_LIST') IS NOT NULL DROP TABLE #FJ_LIST;
    CREATE TABLE #FJ_LIST (RN INT IDENTITY(1,1), FJ_ASSEMBLY_SEQ INT);

    IF OBJECT_ID('tempdb..#SUB_EQUIP_LIST') IS NOT NULL DROP TABLE #SUB_EQUIP_LIST;
    CREATE TABLE #SUB_EQUIP_LIST (RN INT IDENTITY(1,1), WORK_CNTR_SEQ INT, WORK_CNTR_CD VARCHAR(20));

    /* -------------------------------------------------------------------------
       2. 가상 타임라인 초기화
       - 각 프로젝트-항차의 모든 설비와 FJ 시작 시간을 SHIP_TS_POINT로 설정
    ------------------------------------------------------------------------- */
    INSERT INTO #V_WORK_CNTR_TIMESTAMP (SALE_OPP_NO, PJT_SHIP, PROCESS_CODE, WORK_CNTR_CD, TIMESTAMP_POINT)
    SELECT DISTINCT S.SALE_OPP_NO, S.PJT_SHIP, S.PROCESS_CODE, S.WORK_CNTR_CD, M.SHIP_TS_POINT
    FROM #SRC_FJ S
    JOIN #SHIP_META M ON S.SALE_OPP_NO = M.SALE_OPP_NO AND S.PJT_SHIP = M.PJT_SHIP;

    INSERT INTO #V_FJ_READY_TS (SALE_OPP_NO, PJT_SHIP, LOT_NO, ASSEMBLY_SEQ, FJ_ASSEMBLY_SEQ, READY_TS)
    SELECT DISTINCT S.SALE_OPP_NO, S.PJT_SHIP, S.LOT_NO, S.ASSEMBLY_SEQ, S.FJ_ASSEMBLY_SEQ, M.SHIP_TS_POINT
    FROM #SRC_FJ S
    JOIN #SHIP_META M ON S.SALE_OPP_NO = M.SALE_OPP_NO AND S.PJT_SHIP = M.PJT_SHIP;

    /* -------------------------------------------------------------------------
       3. 메인 가상 스케줄링 루프 (기존 AUTO_SCHEDULER 로직 이식)
    ------------------------------------------------------------------------- */
    DECLARE
          @SALE_OPP_NO VARCHAR(20), @PJT_SHIP INT, @SHIP_SEQ INT, @SHIP_SEQ_LOT INT, @LOT_NO VARCHAR(50)
        , @ATWRT02 VARCHAR(50), @ASSEMBLY_SEQ INT, @ASSEMBLY FLOAT
        , @FJ_ASM_SEQ INT, @FJ_ASSEMBLY FLOAT, @FJ_LAST_ASM_SEQ INT
        , @SUL_NO VARCHAR(50), @REV_SEQ VARCHAR(4), @EQUIP_SPEED FLOAT, @LEAD_TIME INT
        , @READY_TS INT, @START_TS INT, @END_TS INT, @WORK_CNTR_SEQ INT
        , @PROCESS_SEQ INT, @PROCESS_CODE VARCHAR(20), @CHOSEN_EQUIP VARCHAR(20), @CUR_TS INT
        , @CHOSEN_GRP_EQUIP VARCHAR(20), @CUR_GRP_TS INT;

    -- [CUR_LOT] 항차 내 우선순위 적용: SHIP_SEQ DESC (높은게 먼저)
    DECLARE CUR_LOT CURSOR LOCAL FAST_FORWARD FOR
    SELECT SALE_OPP_NO, PJT_SHIP, SHIP_SEQ, SHIP_SEQ_LOT, LOT_NO, SUL_NO, REV_SEQ, ATWRT02, ASSEMBLY_SEQ
    FROM #LOT_ORDER
    GROUP BY SALE_OPP_NO, PJT_SHIP, SHIP_SEQ, SHIP_SEQ_LOT, LOT_NO, SUL_NO, REV_SEQ, ATWRT02, ASSEMBLY_SEQ
    ORDER BY PJT_SHIP ASC, SHIP_SEQ DESC, SHIP_SEQ_LOT ASC, MIN(ASSIGN_SEQ) ASC;

    OPEN CUR_LOT;
    FETCH NEXT FROM CUR_LOT INTO @SALE_OPP_NO, @PJT_SHIP, @SHIP_SEQ, @SHIP_SEQ_LOT, @LOT_NO, @SUL_NO, @REV_SEQ, @ATWRT02, @ASSEMBLY_SEQ;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- 1) 공정 리스트 구성
        TRUNCATE TABLE #PROC_LIST;
        INSERT INTO #PROC_LIST(PROCESS_SEQ, PROCESS_CODE)
        SELECT DISTINCT PROCESS_SEQ, PROCESS_CODE FROM #LOT_ORDER 
        WHERE SALE_OPP_NO = @SALE_OPP_NO AND LOT_NO = @LOT_NO AND ASSEMBLY_SEQ = @ASSEMBLY_SEQ
        ORDER BY PROCESS_SEQ;

        -- 2) FJ 리스트 구성
        TRUNCATE TABLE #FJ_LIST;
        INSERT INTO #FJ_LIST(FJ_ASSEMBLY_SEQ)
        SELECT DISTINCT FJ_ASSEMBLY_SEQ FROM #SRC_FJ 
        WHERE SALE_OPP_NO = @SALE_OPP_NO AND LOT_NO = @LOT_NO AND ASSEMBLY_SEQ = @ASSEMBLY_SEQ
        ORDER BY FJ_ASSEMBLY_SEQ;

        SELECT @FJ_LAST_ASM_SEQ = MAX(FJ_ASSEMBLY_SEQ) FROM #FJ_LIST;

        -- 3) 공정 파이프라인 루프
        DECLARE @P_RN INT = 1, @P_CNT INT = (SELECT COUNT(*) FROM #PROC_LIST);
        WHILE @P_RN <= @P_CNT
        BEGIN
            SELECT @PROCESS_SEQ = PROCESS_SEQ, @PROCESS_CODE = PROCESS_CODE FROM #PROC_LIST WHERE RN = @P_RN;

            -- (A) 설비 선택 (가상 타임스탬프 #V_WORK_CNTR_TIMESTAMP 참조)
            SET @CHOSEN_EQUIP = ''; SET @CUR_TS = 0;

            IF @PROCESS_CODE IN ('LDS','UST')
            BEGIN
                SELECT TOP 1 @CHOSEN_EQUIP = WORK_CNTR_CD, @CUR_TS = TIMESTAMP_POINT
                FROM #V_WORK_CNTR_TIMESTAMP
                WHERE PJT_SHIP = @PJT_SHIP AND PROCESS_CODE = @PROCESS_CODE
                  AND EXISTS (SELECT 1 FROM #WC_GRP G WHERE G.SIMUL_PROCESS_CD = @PROCESS_CODE AND G.GRP_WORK_CNTR_CD = WORK_CNTR_CD AND G.WORK_CNTR_CD = WORK_CNTR_CD)
                ORDER BY TIMESTAMP_POINT ASC;
                SET @CHOSEN_GRP_EQUIP = @CHOSEN_EQUIP;
            END
            ELSE IF @PROCESS_CODE = 'INS'
            BEGIN
                SELECT TOP 1 @CHOSEN_EQUIP = WORK_CNTR_CD, @CUR_TS = TIMESTAMP_POINT
                FROM #V_WORK_CNTR_TIMESTAMP
                WHERE PJT_SHIP = @PJT_SHIP AND PROCESS_CODE = @PROCESS_CODE
                  AND ((ISNULL(@ATWRT02, '') = '3' AND WORK_CNTR_CD IN ('INS044', 'INS048', 'INS049'))
                    OR (ISNULL(@ATWRT02, '') = '1' AND WORK_CNTR_CD IN ('INS050', 'INS051', 'INS052')))
                    AND EXISTS (SELECT 1 FROM #WC_GRP G WHERE G.SIMUL_PROCESS_CD = @PROCESS_CODE AND G.GRP_WORK_CNTR_CD = WORK_CNTR_CD AND G.WORK_CNTR_CD = WORK_CNTR_CD)
                ORDER BY TIMESTAMP_POINT ASC;
            END
            ELSE -- CST, WSD 등 기타 공정
            BEGIN
                SELECT TOP 1 @CHOSEN_EQUIP = WORK_CNTR_CD, @CUR_TS = TIMESTAMP_POINT
                FROM #V_WORK_CNTR_TIMESTAMP
                WHERE PJT_SHIP = @PJT_SHIP AND PROCESS_CODE = @PROCESS_CODE
                  AND EXISTS (SELECT 1 FROM #WC_GRP G WHERE G.SIMUL_PROCESS_CD = @PROCESS_CODE AND G.GRP_WORK_CNTR_CD = WORK_CNTR_CD AND G.WORK_CNTR_CD = WORK_CNTR_CD)
                ORDER BY TIMESTAMP_POINT ASC;
            END

            -- (B) FJ 루프
            DECLARE @FJ_RN INT = 1, @FJ_CNT INT = (SELECT COUNT(*) FROM #FJ_LIST);
            WHILE @FJ_RN <= @FJ_CNT
            BEGIN
                SELECT @FJ_ASM_SEQ = FJ_ASSEMBLY_SEQ FROM #FJ_LIST WHERE RN = @FJ_RN;

                -- Skip Rules (SMA, FJY/FJT 등 기존 로직)
                IF (@PROCESS_CODE = 'SMA' AND @FJ_ASM_SEQ <> @FJ_LAST_ASM_SEQ) BEGIN SET @FJ_RN += 1; CONTINUE; END

                -- LDS/UST 그룹 설비 전개 (상세 로직은 기존과 동일하므로 생략하거나 통합 처리)
                -- ... [기존 LDS/UST 서브 설비 루프 삽입 가능] ...

                -- 기본 단일 설비 배정 로직
                SELECT @LEAD_TIME = LEAD_TIME_DAYS, @WORK_CNTR_SEQ = WORK_CNTR_SEQ FROM #SRC_FJ 
                WHERE SALE_OPP_NO = @SALE_OPP_NO AND LOT_NO = @LOT_NO AND PROCESS_CODE = @PROCESS_CODE AND FJ_ASSEMBLY_SEQ = @FJ_ASM_SEQ AND WORK_CNTR_CD = @CHOSEN_EQUIP;

                SELECT @READY_TS = READY_TS FROM #V_FJ_READY_TS 
                WHERE PJT_SHIP = @PJT_SHIP AND LOT_NO = @LOT_NO AND FJ_ASSEMBLY_SEQ = @FJ_ASM_SEQ;

                -- 가상 START/END 계산
                SET @START_TS = CASE WHEN @CUR_TS > @READY_TS THEN @CUR_TS ELSE @READY_TS END;
                SET @END_TS = @START_TS + ISNULL(@LEAD_TIME, 0);

                -- [핵심] 가상 결과 저장
                INSERT INTO #VIRTUAL_RESULT (SALE_OPP_NO, PJT_SHIP, LOT_NO, PROCESS_CODE, WORK_CNTR_CD, V_STRT_TS, V_END_TS, SEQ)
                SELECT @SALE_OPP_NO, @PJT_SHIP, @LOT_NO, @PROCESS_CODE, @CHOSEN_EQUIP, @START_TS, @END_TS, SEQ
                FROM #SRC_FJ WHERE SALE_OPP_NO = @SALE_OPP_NO AND LOT_NO = @LOT_NO AND PROCESS_CODE = @PROCESS_CODE AND FJ_ASSEMBLY_SEQ = @FJ_ASM_SEQ AND WORK_CNTR_CD = @CHOSEN_EQUIP;

                -- 가상 타임라인 업데이트
                UPDATE #V_WORK_CNTR_TIMESTAMP SET TIMESTAMP_POINT = @END_TS + @P_PREP_FJ_DAYS
                WHERE PJT_SHIP = @PJT_SHIP AND PROCESS_CODE = @PROCESS_CODE AND WORK_CNTR_CD = @CHOSEN_EQUIP;

                UPDATE #V_FJ_READY_TS SET READY_TS = @END_TS + @P_PREP_PROC_DAYS
                WHERE PJT_SHIP = @PJT_SHIP AND LOT_NO = @LOT_NO AND FJ_ASSEMBLY_SEQ = @FJ_ASM_SEQ;

                SET @FJ_RN += 1;
            END
            SET @P_RN += 1;
        END
        FETCH NEXT FROM CUR_LOT INTO @SALE_OPP_NO, @PJT_SHIP, @SHIP_SEQ, @SHIP_SEQ_LOT, @LOT_NO, @SUL_NO, @REV_SEQ, @ATWRT02, @ASSEMBLY_SEQ;
    END
    CLOSE CUR_LOT; DEALLOCATE CUR_LOT;
END