CREATE PROCEDURE [dbo].[SP_CABLE_PRODUCTION_GET_SHIPMENT_START_SCHEDULER]
(
      @TIMESTAMP_BASE_DATE            DATE
    , @TB_PROCESS_WORK_CNTR_TIMESTAMP dbo.UDT_MST_PROCESS_WORK_CNTR_TIMESTAMP READONLY
    , @TB_PRIORITY_PJT_LOT_LEADTIME   dbo.UDT_DATA_CABLE_PJT_LOT_FJ READONLY
    , @TB_FIXED_PJT_LOT_TIMESTAMP     dbo.UDT_DATA_CABLE_PJT_LOT_FJ READONLY
    , @P_TEMP_VERSION                 VARCHAR(50)
    , @P_USER_CODE                    VARCHAR(50)
    , @P_SENS_BEFORE                  INT = 0
    , @P_SENS_AFTER                   INT = 0
    , @P_ALLOW_OVERLAP                INT = 0
    , @P_PREP_PROC_DAYS               INT = 1
    , @P_PREP_FJ_DAYS                 INT = 1
)
AS
BEGIN
    SET NOCOUNT ON;

    -- 1. 임시 테이블 생성 (기존 구조 + 항차별 계산용 추가)
    IF OBJECT_ID('tempdb..#WORK_CNTR_TIMESTAMP') IS NOT NULL DROP TABLE #WORK_CNTR_TIMESTAMP;
    IF OBJECT_ID('tempdb..#FIXED_PJT_LOT_DATA') IS NOT NULL DROP TABLE #FIXED_PJT_LOT_DATA;
    IF OBJECT_ID('tempdb..#LOCAL_SHIP_SCHEDULE') IS NOT NULL DROP TABLE #LOCAL_SHIP_SCHEDULE;
    IF OBJECT_ID('tempdb..#FINAL_ASSIGN_DATA') IS NOT NULL DROP TABLE #FINAL_ASSIGN_DATA;

    -- 최종 할당 데이터를 담을 테이블 (SELECT 프로시저와 호환)
    CREATE TABLE #FINAL_ASSIGN_DATA (
        SALE_OPP_NO VARCHAR(20), PJT_SHIP INT, LOT_NO VARCHAR(50), 
        PROCESS_CODE VARCHAR(20), WORK_CNTR_CODE VARCHAR(20),
        STRT_TS INT, END_TS INT, IS_MANUAL BIT
    );

    -- 2. INIT: 기초 데이터 및 설비 타임스탬프 초기화
    EXEC dbo.SP_CABLE_PRODUCTION_GET_SHIPMENT_START_SCHEDULER_INIT 
        @TIMESTAMP_BASE_DATE, @TB_PROCESS_WORK_CNTR_TIMESTAMP, @TB_PRIORITY_PJT_LOT_LEADTIME, @TB_FIXED_PJT_LOT_TIMESTAMP;

    -- 3. RUN: 항차별 독립 계산 및 우선순위 기반 머지 수행
    EXEC dbo.SP_CABLE_PRODUCTION_GET_SHIPMENT_START_SCHEDULER_RUN 
        @P_SENS_BEFORE, @P_SENS_AFTER, @P_ALLOW_OVERLAP, @P_PREP_PROC_DAYS, @P_PREP_FJ_DAYS;

    -- 4. SELECT: 결과 반환 (기존 SELECT 프로시저 재사용 가능하도록 데이터 구성)
    EXEC dbo.SP_CABLE_PRODUCTION_GET_AUTO_SCHEDULER_SELECT 
        @TIMESTAMP_BASE_DATE, @P_TEMP_VERSION, @P_USER_CODE;
END